# Generated by Django 5.0.7 on 2024-12-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='recipieImg/blank.jpg', upload_to='recipieImg'),
        ),
    ]
